### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by Electromorphous** [Electromorphous/DeNotes#4]
Design a logo and add it in the assets folder

**Comment by Vijayabaskar56** [comment]
I can do that, can u assign it to me

**Comment by Vijayabaskar56** [comment]
![deNote-logo3](https://github.com/Electromorphous/DeNotes/assets/84858449/49431e90-aa18-468a-b586-e5f69bf6d9d1)
![deNote-logo2](https://github.com/Electromorphous/DeNotes/assets/84858449/8b2a16e3-5263-4128-a271-c32db77526fc)
![deNote-logo1](https://github.com/Electromorphous/DeNotes/assets/84858449/d5a53ce1-21a9-4336-a2c0-eeab1d1c6edd)
Are any of this OK ?

**Comment by Electromorphous** [comment]
Third one looks great, please add it in the assets and open a PR 👍 
Also please make it a bit brighter, its too gray

and please make an alternative for light mode as well.

**Comment by Vijayabaskar56** [comment]
Got it , will do ✌️.

**Comment by Electromorphous** [comment]
Please use the zinc pallet from here to keep it consistent with the app

https://tailwindcss.com/docs/customizing-colors

**Comment by Vijayabaskar56** [comment]
hey, I got you review on the PR. Here are the Changes that I made can u check it please, just need a confirmation before PR
![Deno-logo-dark](https://github.com/Electromorphous/DeNotes/assets/84858449/49875c8d-5c13-4327-9e47-db5a94c3135a)
![Denote-logo-light](https://github.com/Electromorphous/DeNotes/assets/84858449/a263bf34-2b3b-42be-a6be-2a20a304d951)
