### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by iqrafirdose** [Electromorphous/DeNotes#8]
As read me is an important File. There are some typos in the read-me file.I would like to correct it.

**Comment by iqrafirdose** [comment]
Can you please assign this issue to me under hackthoberfest?

**Comment by Electromorphous** [comment]
Well hacktoberfest has ended and the PRs will not be counted towards hacktoberfest anymore, but you can still do it.

Also, you can still open PRs without the issues being assigned to you, just thought I should let you know. I mean if you had opened the PR yesterday (October 31st) and I accepted it today or tomorrow, it would have counted for hacktoberfest.

**Comment by iqrafirdose** [comment]
> Well hacktoberfest has ended and the PRs will not be counted towards hacktoberfest anymore, but you can still do it.
> 
> Also, you can still open PRs without the issues being assigned to you, just thought I should let you know. I mean if you had opened the PR yesterday (October 31st) and I accepted it today or tomorrow, it would have counted for hacktoberfest.

Ok, I created a PR, can you please review it ?
